export const LOAD_PATIENTS = 'LOAD_PATIENTS';
export const LOAD_PATIENTS_SUCCESS = 'LOAD_PATIENTS_SUCCESS';
export const LOAD_PATIENTS_FAILURE = 'LOAD_PATIENTS_FAILURE';

export const CREATE_PATIENT = 'CREATE_PATIENT';
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAILURE = 'CREATE_PATIENT_FAILURE';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE';
